name = "site"
compatibility_date = "2024-10-01"

main = "./public/_worker.js"

[assets]
directory = "./public"

[observability.logs]
enabled = false
invocation_logs = true

[observability.traces]
enabled = false
